//products
export const ADD_PRODUCTS = "ADD_PRODUCTS";
export const START_LOADING_PRODUCTS = "START_LOADING_PRODUCTS";
export const SUCCESS_LOADING_PRODUCTS = "SUCCESS_PRODUCTS";
export const ERROR_LOADING_PRODUCTS = "ERROR_PRODUCTS";

//Actions occuring on products/:id
export const START_LOADING_PRODUCT = "START_LOADING_PRODUCT";
export const SUCCESS_LOADING_PRODUCT = "SUCCESS_LOADING_PRODUCT";

//categories

export const ADD_CATEGORY = "ADD_CATEGORY";
