
export const ADD_PRODUCTS = "ADD_PRODUCTS";
export const START_LOADING_PRODUCTS = "START_LOADING_PRODUCTS";
export const SUCCESS_LOADING_PRODUCTS = "SUCCESS_PRODUCTS";
export const ERROR_LOADING_PRODUCTS = "ERROR_PRODUCTS";



export const START_LOADING_PRODUCT = "START_LOADING_PRODUCT";
export const SUCCESS_LOADING_PRODUCT = "SUCCESS_LOADING_PRODUCT";
export const SUCCESSFULLY_CREATED_PRODUCT = "SUCCESSFULLY_CREATED_PRODUCT";


export const SUCCESSFULLY_CREATED_CATEGORIES = "SUCCESSFULLY_CREATED_CATEGORIES";


 


export const SUCCESS_LOADING_PRODUCT_CATEGORIES = "SUCCESS_PRODUCT_CATEGORIES";

